### ISSUE TITLE
Editor becomes very slow when there are a lot of nodes inside

### ISSUE THREAD

**Issue by alextitonis** [super-reality/thoth#2]

**Comment by michaelsharpe** [comment]
The current implementation of saving may contribute to this. On every action the whole spell is serialized and sent to the server for saving. I have wanted to create a save system that only sends the changes between the old graph and current one to the server for saving. 

In theory I have also though that the JSOn could be stored in a graph database lie Neo4J. then each node has independent existence in the DB and could be synced and saved more easily.

**Comment by michaelsharpe** [comment]
Oh. Also could be solved with sub spells. Being able to take a whole group of nodes and convert into their own spell that runs as its own component in the current spell. I made modules to do this. But a module and spell are the same data structure so the module data structure and concept can be dropped and everything is a spell.

**Comment by lalalune** [comment]
@michaelsharpe I think a quick fix is to enable/disable autosave and allow manual save. I actually find autosave to be kind of a liability when I'm experimenting and developing.
This serialization strategy is common for lots of stuff, Blender has the same problem with its autosave system. I think as long as we can turn it off our time is better spent right now on subgraphs than independent serialization. The JSON format makes development and debugging a lot easier.
