### ISSUE TITLE
Fewshot editors aren't saved

### ISSUE THREAD

**Issue by alextitonis** [super-reality/thoth#3]

**Comment by michaelsharpe** [comment]
May be fixed in my 0.0.66 branch on latitude.  I have centralized all saving of spells via diffs into one place, and removed a lot of extraneous spell saves.

**Comment by lalalune** [comment]
Fewshots aren't saving at all in our current branch at least

**Comment by lalalune** [comment]
Fewshots aren't saving at all in current build

**Comment by michaelsharpe** [comment]
From the text editor?
