### ISSUE TITLE
Async runner / collector

### ISSUE THREAD

**Issue by lalalune** [super-reality/thoth#5]
Right now our execution is linear. One trigger out. We want to be able to run multiple things in parallel. To do this we can make a node that fires multiple triggers simultaneously, and another node that collects multiple triggers and waits until they all execute to fire the that node's single trigger.

So one node takes one trigger in, and lets user specific number of trigger outs.

The other node takes multiple user-specified triggers in, waits for all to fire then sends all to a single trigger out.

This way we can handle multiple processes async.

**Comment by michaelsharpe** [comment]
The current engine on the server is only a small amount of logic away from being able to pass a request body option of the name of a trigger to start the chain running on. I had always intended that a spell could have multiple trigger inputs defined and the requester could specify which of them they wanted to start running from.
