### ISSUE TITLE
Replace all SQL calls in server with Prisma API calls

### ISSUE THREAD

**Issue by lalalune** [super-reality/thoth#59]
Right now we're doing a lot of very basic SQL inside of the server, but this ends up being very fragile, untyped and not flexible for different types of calls we might want to make.

We should replace all of the SQL where possible with API calls into the Prisma models, and try to keep everything typed

**Comment by kinjalravel** [comment]
@lalalune we should use this  https://www.prisma.io/ instead of Sequeelize

**Comment by michaelsharpe** [comment]
A couple of comments here.  The goal for latitude with this is to separate out all thoth running from our main API.  This benefits both scalability and development experience.  The only thing we need really is for some kind of user adapter that will let us use our own user object and user ID for all relationships in Thoths systems. That way the data model will line up with our SSO for our users.
